app:
  models:
    embedding:
      type: "huggingface"
#      model: "BAAI/bge-reranker-base"
      model: "BAAI/bge-large-en-v1.5"
#      model: "BAAI/bge-large-en-v1.5"
    llm:
      type: "gemini"
      model: "gemini-2.0-flash-exp"
    chatllm:
      type: "gemini"
      model: "gemini-2.0-flash-exp"
    rerank:
#      type: "bge"
#      model: "BAAI/bge-reranker-base"
#      model: "BAAI/bge-reranker-large"
#      model: "BAAI/bge-small-en-v1.5"
      type: "cross-encoder"
      model: "cross-encoder-ms-marco-MiniLM-L-12-v2"
#      model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  embedding:
    input_path: "./data/input"
    staging_path: "./data/staging"
    archive_path: "./data/archive"
    trunk_size: 2048
    overlap: 256
    vector_store:
      enabled: true
      type: "qdrant"
      # type: "redis"
      # type: "pgvector"
      collection_name: "rag_docs"
      cache_collection_name: "response_cache"
    graph_store:
      enabled: true
      type: "neo4j"
  query_agent:
    search:
      provider: "duckduckgo"
      rerank_enabled: true
      query_expansion_enabled: true
      graph_search_enabled: true
      hypothetical_answer_enabled: true
      web_search_enabled: true
      max_retries: 1 # max retry for query rewrite
      top_k: 5 # for retrieval top n documents, equal to max_documents
      relevance_threshold: 9.0 # for filter out low relevance documents
      query_rewrite_enabled: true
    grading: # for fact checking, the lower of the score, the higher risk of hallucination
      minimum_score: 0.7
    output:
      generate_suggested_documents: true
      generate_citations: true
      format:
        default: markdown
        detect_from_query: true
        include_metadata: true
    metrics:
      enabled: true
      store_in_db: true
      log_level: "INFO"
  proxy:
    enabled: true
    no_proxy: "localhost,127.0.0.1"
    http_proxy: "http://127.0.0.1:7897"
    https_proxy: "http://127.0.0.1:7897"
  logging.level:
    root: "DEBUG"  # default for all packages including project and libraries
    utils.lock: "WARNING"
    langchain: "WARNING"
    httpx: "WARNING"
